# Generated by Django 4.1.2 on 2023-04-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-end_date"]},
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="avatar.png", upload_to=""),
        ),
    ]
